[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
DISABLE_WHATSAPP = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"